name: notary_ping_notary
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  flutter_staggered_animations: ^1.1.1
  pinput: ^3.0.1
  avatar_glow: ^2.0.2
  expandable_page_view: ^1.0.17
  intl:
  delayed_display: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/onboarding-vectors/
    - assets/icon/



  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-VariableFont.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: fonts/montserrat/Montserrat-Medium.ttf
    - family: Montserrat-Light
      fonts:
        - asset: fonts/montserrat/Montserrat-Light.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/montserrat/Montserrat-Bold.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-VariableFont.ttf
    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
    - family: Inter-Light
      fonts:
        - asset: fonts/Inter/Inter-Light.ttf
    - family: Inter-Medium
      fonts:
        - asset: fonts/Inter/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: fonts/Inter/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: fonts/Inter/Inter-Bold.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: fonts/Inter/Inter-ExtraBold.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/oxygen/Oxygen-Regular.ttf
    - family: Oxygen-Light
      fonts:
        - asset: fonts/oxygen/Oxygen-Light.ttf
    - family: Oxygen-Bold
      fonts:
        - asset: fonts/oxygen/Oxygen-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
